# Generated by Django 5.0.14 on 2025-12-30 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('cursor_position', models.JSONField(blank=True, default=dict, help_text='Current cursor position in document')),
                ('current_block_id', models.UUIDField(blank=True, null=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
            ],
            options={
                'db_table': 'collaboration_sessions',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('operation_type', models.CharField(help_text='insert, delete, update, move, etc.', max_length=50)),
                ('payload', models.BinaryField(help_text='CRDT update in binary format')),
                ('version', models.PositiveIntegerField(db_index=True)),
                ('client_id', models.CharField(max_length=100)),
                ('timestamp', models.BigIntegerField(db_index=True, help_text='High-precision timestamp for ordering')),
            ],
            options={
                'db_table': 'operation_logs',
                'ordering': ['version', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PresenceAwareness',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('state', models.JSONField(default=dict, help_text='User awareness state (cursor, selection, etc.)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'presence_awareness',
            },
        ),
    ]
