# Generated by Django 5.0.14 on 2025-12-30 06:06

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, help_text='For videos/audio', null=True)),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('heading1', 'Heading 1'), ('heading2', 'Heading 2'), ('heading3', 'Heading 3'), ('bulleted_list', 'Bulleted List'), ('numbered_list', 'Numbered List'), ('todo', 'To-do'), ('toggle', 'Toggle'), ('quote', 'Quote'), ('callout', 'Callout'), ('code', 'Code'), ('equation', 'Equation'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('embed', 'Embed'), ('page', 'Page'), ('database', 'Database'), ('divider', 'Divider'), ('toc', 'Table of Contents')], db_index=True, default='text', max_length=30)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Block content in structured format')),
                ('text', models.TextField(blank=True, help_text='Plain text extraction for full-text search')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Block-specific settings (color, checked, language, etc.)')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'db_table': 'blocks',
                'ordering': ['tree_id', 'lft', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.JSONField(help_text='Rich text content')),
                ('text', models.TextField(blank=True, help_text='Plain text for search')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='Untitled', max_length=500)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='document_covers/%Y/%m/')),
                ('cover_position', models.FloatField(default=0.5)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('state', models.JSONField(blank=True, default=dict, help_text='Collaborative editing state (CRDT)')),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('is_template', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked documents cannot be edited')),
                ('is_public', models.BooleanField(default=False)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('position', models.FloatField(db_index=True, default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Custom properties (select, multi-select, date, etc.)')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
            ],
            options={
                'db_table': 'document_permissions',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('state', models.JSONField(default=dict)),
                ('blocks_snapshot', models.JSONField(default=list)),
                ('change_summary', models.TextField(blank=True)),
                ('change_type', models.CharField(default='edit', help_text='manual_save, auto_save, restore, etc.', max_length=50)),
                ('content_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
            ],
            options={
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
