# Generated by Django 5.0.14 on 2025-12-30 06:06

import django.contrib.postgres.indexes
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='block',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.block'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.block'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='block',
            field=models.ForeignKey(blank=True, help_text='Specific block this comment is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.block'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.board'),
        ),
        migrations.AddField(
            model_name='document',
            name='board_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='workspaces.boardlist'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='block',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='documents.document'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'is_deleted'], name='documents_workspa_fbf80c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['board', 'board_list', 'position'], name='documents_board_i_418218_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by'], name='documents_created_32bb74_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['last_edited_at'], name='documents_last_ed_7b31f0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='documents_tags_b3492b_gin'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['properties'], name='documents_propert_3b546b_gin'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['document', 'is_resolved'], name='comments_documen_c1c7fa_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['block', 'parent'], name='comments_block_i_4bd772_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='comments_author__b3902f_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['document', 'parent'], name='blocks_documen_dc60fb_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['block_type'], name='blocks_block_t_a60150_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['position'], name='blocks_positio_a10cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='blocks_content_339cf8_gin'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=django.contrib.postgres.indexes.GinIndex(fields=['properties'], name='blocks_propert_46f981_gin'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['tree_id', 'lft'], name='documents_block_tree_id_lf666d'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['document'], name='attachments_documen_ca8d30_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['block'], name='attachments_block_i_97e2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['document', 'role'], name='document_pe_documen_dd3dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['user'], name='document_pe_user_id_07267e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'user')},
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='document_ve_documen_c3917c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['created_at'], name='document_ve_created_c8d81d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
