# Generated by Django 5.0.14 on 2025-12-30 07:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Block content in structured format', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Block-specific settings (color, checked, language, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Custom properties (select, multi-select, date, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='state',
            field=models.JSONField(blank=True, default=dict, help_text='Collaborative editing state (CRDT)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='blocks_snapshot',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='state',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
