# Generated by Django 5.0.14 on 2025-12-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences and settings', null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
