# Generated by Django 5.0.14 on 2025-12-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Workspace settings and configuration', null=True),
        ),
    ]
