# Generated by Django 5.0.14 on 2025-12-31 18:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_board_settings_alter_workspace_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='card_covers/%Y/%m/')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=list, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_cards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_cards', to='workspaces.boardlist')),
            ],
            options={
                'db_table': 'board_cards',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['list', 'position'], name='board_cards_list_id_6deff5_idx'), models.Index(fields=['due_date'], name='board_cards_due_dat_44fcd1_idx'), models.Index(fields=['is_archived'], name='board_cards_is_arch_78de5b_idx')],
            },
        ),
    ]
