# Generated by Django 5.0.14 on 2025-12-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_add_card_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='labels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
