# Generated by Django 5.0.14 on 2026-01-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_cardcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlist',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done'), ('custom', 'Custom')], default='custom', help_text='Status category for this list', max_length=20),
        ),
        migrations.AddField(
            model_name='cardcomment',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs or file paths', null=True),
        ),
    ]
