# Generated by Django 5.0.14 on 2026-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_add_status_to_boardlist_and_images_to_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', help_text='Current status of the card', max_length=20),
        ),
    ]
