# Generated by Django 5.0.14 on 2025-12-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
