# Generated by Django 5.0.14 on 2026-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mentioned in comment'), ('comment', 'New comment'), ('share', 'Document shared'), ('invite', 'Workspace invitation'), ('assignment', 'Assigned to task'), ('due_date', 'Due date reminder'), ('workspace', 'Workspace event'), ('system', 'System notification')], max_length=20),
        ),
    ]
